config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "accounts#index"

  resources :banks, except: :show
  resources :categories, except: :show
  resources :transactions, except: :show

  get "group" => "accounts#group"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :account
  has_many :transactions
  has_one_attached :icon

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  def index
    @categories = Category.account(current_user.account)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.account_id = current_user.account.id

    if @category.save
      redirect_to root_path, notice: t(".created", name: @category.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to root_path, notice: t(".updated", name: @category.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.transactions.exists?
      redirect_to root_path, alert: t("common.exist_relation", model: t("common.category"), name: @category.name)
    else
      @category.destroy
      redirect_to root_path, status: :see_other, notice: t(".deleted")
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def set_category
    @category ||= Category.find(params[:id])
  end
end

app/views/categories/_category.html.erb
<%= link_to edit_category_path(category.id), data: { turbo_frame: "modal" }, class: "flex items-center gap-2 bg-white shadow my-1 rounded-lg px-2 py-1 hover:bg-gray-100" do %>
  <%= image_tag category.icon, class: "w-7 h-7" if category.icon.attached? %>
  <%= category.name %>
<% end %>

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= f.label :name, class: "block mb-2 text-sm text-gray-700 font-medium" %>
    <%= f.text_field :name, autofocus: true, class: "py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none" %>
  </div>

  <div>
    <%= f.label :icon, class: "block mb-2 text-sm text-gray-700 font-medium" %>
    <%= f.label :icon, class: "block font-medium cursor-pointer min-w-72 py-2 text-center text-gray-700 border-2 border-[#cacaca] border-dashed rounded-lg hover:bg-gray-50" do %>
      <span class="span-files">
        <%= t('.select_icon') %>
      </span>
    <% end %>
    <%= f.file_field :icon, class: "w-[0.1px] h-[0.1px] absolute -z-10 inputfile" %>
  </div>

  <div class="mt-4 w-full flex gap-3" data-controller="sweetalert">
    <%= f.submit class: "bg-main-color text-white rounded p-2 w-full" %>
    <% if action_name == 'edit' %>
      <a data-action="click->sweetalert#delete" data-parameters='{"id": <%= @category.id %>, "model": "categories"}' class="bg-main-color text-white rounded p-2 w-full text-center"><%= t('.delete') %></a>
    <% end %>
  </div>
<% end %>

<script>
  const $input = document.querySelector('.inputfile')
  
  $input.addEventListener('change', (e) => {
    const $label = document.querySelector('.span-files')
    $label.innerText = e.target.files[0].name
  })
</script>

app/views/categories/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <section data-modal-target="float"  class="absolute z-20 bg-white top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 p-5 rounded-2xl shadow-md ease-in-out duration-300 scale-0 max-w-[90%]">
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-xl font-bold text-main-color"><%= t('.title') %></h2>
        <div data-action="click->modal#close" class="flex gap-1 items-center cursor-pointer">
          <%= image_tag "icons/close.svg", class: "w-6 h-6" %>
        </div>
      </div>

      <%= render "form" %>
    </section>
  </div>
<% end %>

app/views/categories/index.html.erb
<%= render partial: "category", collection: @categories %>