config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "accounts#index"

  resources :banks, except: :show
  resources :categories, except: :show
  resources :transactions, except: :show

  get "group" => "accounts#group"
end

app/models/account.rb
class Account < ApplicationRecord
  after_save :create_bank

  belongs_to :user
  belongs_to :parent, class_name: "User", optional: true
  has_many :banks, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :transactions, dependent: :destroy

  def create_bank
    Bank.create(name: "My money", balance: 0, account_id: id)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    account_id = current_user.account.id
    start_month = Date.new(Date.current.strftime("%Y").to_i, Date.current.strftime("%m").to_i, 1)
    end_month = start_month.end_of_month

    @all_transactions = Transaction.account(account_id).where(date: start_month..end_month).load_async
    @categories = Category.with_attached_icon.account(account_id).load_async
    @banks = Bank.with_attached_picture.with_attached_icon.account(account_id).load_async
    @today_transactions = @all_transactions.select { |t| t.date == Date.today }

    @total_amount_today = 0
    @today_transactions.each do |t|
      if t.transaction_type == 0
        @total_amount_today += t.amount
      else
        @total_amount_today -= t.amount
      end
    end

    @total_balance = 0
    @banks.each { |b| @total_balance += b.balance }

    @total_income = 0
    @total_expense = 0

    @all_transactions.each do |t|
      if t.transaction_type == 0
        @total_income += t.amount
      else
        @total_expense += t.amount
      end
    end
  end

  def group
    @accounts = Account.where(parent_id: current_user.id)
  end

  def add_user_to_group
  end

  def remove_user_from_group
  end
end

app/views/accounts/index.html.erb
 <main class="sm:mx-[25%] lg:mx-3 xl:mx-[10%] flex flex-col lg:flex-row justify-between gap-3 px-2 md:px-0">
  <section class="w-full lg:w-1/5">
    <section class="p-4 md:p-5 bg-white border shadow-sm rounded-xl overflow-y-auto scroll-bar">
      <div class="flex justify-between items-center mb-2">
        <h3 class="text-xl font-semibold text-gray-800"><%= t('.categories') %></h3>
        <%= link_to new_category_path, data: { turbo_frame: "modal" } do %>
          <div class="bg-main-color text-white rounded-lg flex justify-center py-1 px-2 shadow-sm transaction-all duration-300 active:scale-95">
            <%= image_tag "icons/plus.svg", class: "w-5 h-5" %>
            <p><%= t('.add') %></p>
          </div>
        <% end %>
      </div>
      <%= render partial: "categories/category", collection: @categories %>
    </section>
  </section>

  <section class="w-full lg:w-3/5">
    <section class="p-4 md:p-5 bg-white border shadow-sm rounded-xl">
      <div class="flex justify-between items-center mb-4">
        <div>
          <span class="text-sm text-gray-500"><%= t('.transactions') %></span>
          <h3 class="text-xl font-semibold text-gray-800"><%= t('.transactions_today') %></h3>
        </div>
        <div class="flex gap-2">
          <%= link_to t('.all_transactions'), transactions_path, class: "py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 active:scale-95 transaction-all duration-300 text-center" %>
          <%= link_to new_transaction_path, data: { turbo_frame: "modal" } do %>
            <div class="bg-main-color text-white rounded-lg flex justify-center py-2 px-3 shadow-sm transaction-all duration-300 active:scale-95">
              <%= image_tag "icons/plus.svg", class: "w-5 h-5" %>
              <p><%= t('.add') %></p>
            </div>
          <% end %>
        </div>
      </div>
      <% if @today_transactions.empty? %>
        <div class="font-medium text-center mt-5">
          <%= t('.no_transactions') %>
        </div>
      <% else %>
        <div class="overflow-y-auto max-h-[65vh] scroll-bar">
          <table class="min-w-full bg-white shadow-md rounded-lg">
            <thead class="bg-gray-50 border-b">
              <tr>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.transaction_name') %></th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.transaction_description')%></th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.transaction_amount') %></th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.transaction_date') %></th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.transaction_type') %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "transactions/transaction", collection: @today_transactions %>
            </tbody>
            <tfoot class="bg-gray-50 border-b text-center">
              <tr>
                <th colspan="2" class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.total_amount_today') %></th>
                <td><%= @total_amount_today %></td>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-700"><%= t('.transactions_count_today') %></th>
                <td><%= @today_transactions.count %></td>
              </tr>
            </tfoot>
          </table>
        </div>
      <% end %>
    </section>
    <section class="p-4 md:p-5 mt-4 bg-white border shadow-sm rounded-xl w-full">
      <%= line_chart Transaction.group_by_day(:date).count %>
    </section>
  </section>

  <section class="w-full lg:w-1/5 flex flex-col gap-2 lg:gap-3">
    <section class="p-2 md:p-3 bg-white border shadow-sm rounded-xl flex gap-2">
      <span class="py-1 px-1.5 inline-flex items-center gap-x-1 text-xs font-medium bg-teal-100 text-teal-800 rounded-full dark:bg-teal-500/10 dark:text-teal-500">
        <svg class="size-2.5" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        <%= t('.income') %>
      </span>
      <p class="text-gray-700 font-medium">$<%= @total_income %></p>
    </section>
    <section class="p-2 md:p-3 bg-white border shadow-sm rounded-xl flex gap-2">
      <span class="py-1 px-1.5 inline-flex items-center gap-x-1 text-xs font-medium bg-red-100 text-red-800 rounded-full dark:bg-red-500/10 dark:text-red-500">
        <svg class="size-2.5" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <%= t('.expense') %>
      </span>
      <p class="text-gray-700 font-medium">$<%= @total_expense %></p>
    </section>
    <section class="p-2 md:p-3 bg-white border shadow-sm rounded-xl flex gap-2">
      <span class="py-1 px-1.5 inline-flex items-center text-xs font-medium bg-sky-100 text-sky-800 rounded-full">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 56 56"><path fill="currentColor" fill-rule="evenodd" d="M29 30v10c3.519-.316 5-2.287 5-4.89c0-2.507-1.152-3.99-5-5.11m-3-5v-9c-3.273.415-5 2.33-5 4.43s1.364 3.647 5 4.57m2.84.737l1.072.277C35.784 27.423 39 29.917 39 34.836c0 5.658-4.466 8.868-10.16 9.284V48h-2.523v-3.88c-5.672-.439-10.16-3.741-10.317-9.284h4.622c.402 2.702 2.1 4.688 5.695 5.08V29.849l-.916-.231c-5.672-1.363-8.731-3.996-8.731-8.684c0-5.173 4.02-8.591 9.647-9.03V8h2.523v3.903c5.582.462 9.624 3.926 9.803 9.169h-4.645c-.29-2.91-2.3-4.596-5.158-4.966z"/></svg>
        <%= t('.total_balance') %>
      </span>
      <p class="text-gray-700 font-medium">$<%= @total_balance %></p>
    </section>

    <section class="p-4 md:p-5 bg-white border shadow-sm rounded-xl overflow-y-auto scroll-bar">
      <div class="flex justify-between items-center">
        <h3 class="text-xl font-semibold text-gray-800"><%= t('.banks') %></h3>
        <%= link_to new_bank_path, data: { turbo_frame: "modal" } do %>
          <div class="bg-main-color text-white rounded-lg flex justify-center py-1 px-2 shadow-sm transaction-all duration-300 active:scale-95">
            <%= image_tag "icons/plus.svg", class: "w-5 h-5" %>
            <p><%= t('.add') %></p>
          </div>
        <% end %>
      </div>
      <%= render partial: "banks/bank", collection: @banks %>
    </section>
  </section>
</main>
<%= turbo_frame_tag "modal" %>

<style>
  .scroll-bar {
    --sb-track-color: #ffffff;
    --sb-thumb-color: #638c6d;
    --sb-size: 10px;
  }

  .scroll-bar::-webkit-scrollbar {
    width: var(--sb-size)
  }

  .scroll-bar::-webkit-scrollbar-track {
    background: var(--sb-track-color);
    border-radius: 3px;
  }

  .scroll-bar::-webkit-scrollbar-thumb {
    background: var(--sb-thumb-color);
    border-radius: 3px;
  }

  @supports not selector(::-webkit-scrollbar) {
    scroll-bar {
      scrollbar-color: var(--sb-thumb-color)
      var(--sb-track-color);
    }
  }
</style>